# Basic
title: 坚果口袋
subtitle: 学海无涯苦作舟
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: nutocks 的技术博客.
creator: <a href="http://nutit.net">@nutock</a>

url: "http://nutit.net"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 关于, description: 关于, url: '/about'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: kimigao1986
    github: kimigao
    twitter: kimigao1986
    mail: nutocks@gmail.com

# Google Analytics
ga:
    id: UA-29579477-1
    host: www.kimigao.me
